<a href="https://colab.research.google.com/github/obeabi/Assignments/blob/master/Numpy_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy Assignment 
# Written by Abiola Obembe
## Date: 2020-12-26
## Course: ML masters with deployment and deep learning


In [3]:
import numpy as np

## Question 1

Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde

In [108]:
# Write code here

def geom_progression(x,N= 3, increasing= False):
 # where n is the number of columns in output, 
 # increasing is a bool argument: True or False
 # X : output of function
  H = len(x)
  X = np.zeros((H,N))

  for i in range(N):
    for h in range(H):

        if increasing is False:
          order = N -i - 1
          X[h,i] = x[h]**order
        else:
          order = i
          X[h,i] = x[h]**order         
  return X

In [111]:
# test function here
Z = np.array([1,2,3])
X = geom_progression(Z, N= 4, increasing= False)

print(X)

[[ 1.  1.  1.  1.]
 [ 8.  4.  2.  1.]
 [27.  9.  3.  1.]]


## Question 2

Write a function to find moving average in an array over a window:
 Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [98]:
# Write function here
def moving_average(x,k=4):
  n_seq = len(x)
  n_mavg = n_seq-k+1
  y = np.zeros((n_mavg, 1))

  for i in range(n_mavg):
      y[i] = (x[i:i+k].sum())/k

  return  y

In [114]:
# test code here
x= np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
#x = np.linspace(10,100,10)

print("The moving average of array x is \n", np.squeeze(moving_average(x, k = 3)))

The moving average of array x is 
 [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
